Update convert
DS4SD/deepsearch-toolkit pull request #21
Opened 2022-07-05 14:05 UTC by exomishra

2022-07-05 14:12 UTC, PeterStaar-IBM commented on deepsearch/cps/client/components/documents.py
> +        source_file: Optional[Path] = None,
`file` -> `path`

2022-07-05 14:16 UTC, PeterStaar-IBM commented on deepsearch/documents/cli/main.py
>      typer.echo(WELCOME)
keep log clean

2022-07-05 14:26 UTC, PeterStaar-IBM commented on deepsearch/documents/core/convert.py
let's import a small class that does the url black magic.

2022-07-05 14:38 UTC, PeterStaar-IBM commented on deepsearch/documents/core/main.py
> +    source_file : path [OPTIONAL]
file -> path

2022-07-05 14:39 UTC, PeterStaar-IBM reviewed
look at the comments

2022-07-07 08:28 UTC, cau-git requested changes
@exomishra Thanks! This is not bad so far, but there are a couple of things that we need to change.

1. Any use of the parameter `cli_use`, which is passed around in _library_ functions and implements alternative behaviour, must be eliminated. Library functions must have no knowledge that a CLI exists. This is an absolutely critical aspect of proper code design. 
2. I could not clearly see it because the diff is complex, but please check carefully that _not a single `print()`_ is ever used in a library function. Using `print()` is allowed for CLI only methods.
3. There is an inconsistent use of singular and plural, for example:
```
urls = get_download_url(cps_proj_key=self.proj_key, task_ids=self.task_ids)
```
4. Further comments below.

2022-07-07 08:28 UTC, cau-git commented on deepsearch/documents/core/input_process.py
> +        if cli_use == False:
Sorry, we can't do this. This is in a library function and it must not need _any_ knowledge that a CLI even exists.
The CLI implementation should simply use the library classes/method

2022-07-07 08:28 UTC, cau-git commented on deepsearch/cps/client/components/documents.py
> +    def download_json(self, result_dir: Path, progress_bar=False):
Suggests this downloads _one_ JSON. But that is not what it looks like in the code. Please revise the use of plural and singular.

2022-07-07 08:28 UTC, cau-git commented on deepsearch/cps/client/components/documents.py
> +        urls = get_download_url(cps_proj_key=self.proj_key, task_ids=[self.task_id])
Again, watch the use of plural and singular. This suggests that multiple `urls` can be returned, but the expectation is _one_ document.

2022-07-07 08:28 UTC, cau-git commented on deepsearch/documents/core/utils.py
> +        self.url_linked_ccs = (
This looks like dangerous hackery, why are you reverse engineering the linked_ccs URL? It is well defined and one can easily use an URL parser to properly get the base host, path, etc.

I see that in other places you already used `urllib.parse.urlparse`

2022-07-07 08:28 UTC, cau-git commented on deepsearch/documents/core/main.py
> +    cli_use : Boolean (default is False in code, True in CLI)
As explained, a `cli_use` argument is a no-go.

2022-07-07 08:28 UTC, cau-git commented on deepsearch/documents/core/main.py
> +        if urllib.parse.urlparse(url).scheme in ("http", "https"):
What is this supposed to do? Accept URLs with `file://` or such?
Any valid URL must be using `http` or `https` protocol handler, so please remove the extra if/else.

2022-07-10 13:32 UTC, cau-git approved these changes
🚢 Time to ship!

Below remarks to be kept on record for next iterations.

2022-07-10 13:32 UTC, merged

2022-07-10 13:57 UTC, exomishra commented on deepsearch/documents/core/convert.py
> +    if api is None:
Should we create an issue to remind/track this source of problem?